### ISSUE TITLE
Похоже что сама игра поломана. Ошибка которая ломает логику игры начинается с 13 строчки . 

### ISSUE THREAD

**Issue by Muxamedin** [SkyVoskers/HIlel_Vosk_py#2]
https://github.com/SkyVoskers/HIlel_Vosk_py/blob/5e6510ceea8ce645df6308b91458dcb7b7bf6644/Homework_2/Dialog_Script.py#L13

Похоже что сама игра поломана. Ошибка которая ломает логику игры начинается с 13 строчки.
Начиная с 13 линии весь код должен быть смещен на 4 пробела в лево что бы игра заработала.

**Comment by SkyVoskers** [comment]
Исправил

Сб, 24 июля 2021 г. в 17:57, Mikel Bily ***@***.***>:

**Comment by Muxamedin** [comment]
Можно и так
